MTO update for AUPs without mediaTypes
rubicon-project/PPI pull request #1
Opened 2020-10-19 19:20 UTC by mmoschovas

Update to include check for mediaTypes property on matched adUnitPattern, and if not exist, copy over mto. Also added some wanring logs to filtered matches i.e. filtereed by custommapping or size

## Type of change

- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

- test parameters for validating bids
```
{
  bidder: '<bidder name>',
  params: {
    // ...
  }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [ ] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

## Other information

2020-10-20 07:32 UTC, aleksatr commented on modules/ppi/hbInventory/aup/aup.js
> +          utils.logWarn('[PPI] Custom mapping function error:', e);
Expected indentation of 8 spaces but found 10 (eslint)

2020-10-20 07:32 UTC, aleksatr commented on modules/ppi/hbInventory/aup/aup.js
> +(getGlobal()).ppi.setCustomMappingFunction = setCustomMappingFunction;
Newline required at end of file but not found. (eslint)

2020-10-20 07:47 UTC, aleksatr commented on modules/ppi/hbInventory/aup/aup.js
> +export function addMtoToPattern(adUnitPattern) {
hey @mmoschovas , I assume that this function, `mtoConfigMap` and `mtoRevId` property on AUP is coming from the original demand manager, why are we introducing this in PPI given that it's not mentioned in the Tech Spec document?

2020-10-20 08:11 UTC, FilipStamenkovic requested changes
You should fix errors pointed by Aleksa.  

I recommend before each push you should do: `gulp test` to see if tests are passing with your changes. This command would have pointed out linting errors.  

You added new function `addMtoToPattern` I suggest you also add unit tests for that function. For this particular case, `aup_spec.js` would be appropriate place.  

But, the question from Aleksa stands here, 'why do we need this'?  
`mtoConfigMap` is not mentioned in the specs at all, why are we introducing it in the code?  
If it is really needed, I suggest first updating the specs and after that is approved, then we update the code.

2020-10-20 08:11 UTC, FilipStamenkovic commented on modules/ppi/hbInventory/aup/aup.js
> +    adUnitPattern.mediaTypes = pbjs.ppi.mtoConfigMap[adUnitPattern.mtoRevId].mediaTypes;
`mtoConfigMap` is not defined anywhere. This line will always throw an exception.

2020-10-20 12:22 UTC, mmoschovas commented
@FilipStamenkovic I ran gulp test and it passed. I re-ran to make sure and it is still passing, so not sure why you are seeing failures. I'll make fixes pointed out here and repush.

2020-10-20 12:24 UTC, mmoschovas commented on modules/ppi/hbInventory/aup/aup.js
> +    adUnitPattern.mediaTypes = pbjs.ppi.mtoConfigMap[adUnitPattern.mtoRevId].mediaTypes;
This will be defined in the Demand Manager build and should only run in the instance that an MTO does not exist on the AUP

2020-10-20 12:25 UTC, mmoschovas commented on modules/ppi/hbInventory/aup/aup.js
> +export function addMtoToPattern(adUnitPattern) {
I think this was an oversight that was missed in the spec. Without it, Demand Manager cannot work with the PPI module

2020-10-20 12:33 UTC, FilipStamenkovic commented
@mmoschovas running `gulp test` will run `gulp lint`, when `gulp lint` is executed it will remove extra whitespaces and it will add new line at the end of the file.  

When you did run it, probably you didn't notice that `gulp lint` made modifications to `aup.js` code?

2020-10-20 13:02 UTC, mmoschovas commented
Yeah that's what I am confused about. Perhaps I reverted it the first time before pushing in error. Either way I'll repush this once I complete the test.

2020-10-20 13:15 UTC, aleksatr commented on modules/ppi/hbInventory/aup/aup.js
> +export function addMtoToPattern(adUnitPattern) {
If that is the case, why don't we do it on the demand manager side? That way we don't need to have exactly the same function (addMtoToPattern) in both PPI and DM, plus PPI does not need to know anything about `mtoConfigMap` or `mtoRevId` (these concepts can remain purely DM). Before DM calls pbjs.ppi.addAdUnitPatterns(), it can pre-process the AUPs and add MTO from mtoConfigMap where needed. What do you think?

2020-10-20 13:24 UTC, mmoschovas commented on modules/ppi/hbInventory/aup/aup.js
> +export function addMtoToPattern(adUnitPattern) {
We originally had the mediaTypes defined on the patterns themselves. We moved away from this in an effort to reduce wrapper sizes, as many MTOs are repeated throughout the patterns. If we think this will be an issue, we can organize a discussion regarding this concept

2020-10-21 15:38 UTC, naegelin commented on modules/ppi/hbInventory/aup/aup.js
> +    adUnitPattern.mediaTypes = pbjs.ppi.mtoConfigMap[adUnitPattern.mtoRevId].mediaTypes;
Per our call on 10/21/20 this PR is to be merged in.

2020-10-22 08:40 UTC, FilipStamenkovic requested changes

2020-10-22 08:40 UTC, FilipStamenkovic commented on modules/ppi/hbInventory/aup/aup.js
> +    adUnitPattern.mediaTypes = pbjs.ppi.mtoConfigMap[adUnitPattern.mtoRevId].mediaTypes;
What do you think about adding `mediaTypes` to aup when PPI is loaded, or to be more precise in `addAdUnitPatterns` function?  
In that way aups will have mto object when user executes `ppi.requestBids`.  

Also, one more thing, you could initialize `pbjs.ppi.mtoConfigMap`. You said:  
> This will be defined in the Demand Manager build

But, ppi should not depend on demand manager initializing this variable, ppi should work the same even for the publishers that are not using Demand Manager.  
Just add at the bottom:

```
(getGlobal()).ppi.mtoConfigMap = (getGlobal()).ppi.mtoConfigMap || {};
```

2020-10-22 14:24 UTC, mmoschovas commented
Regarding the first point, I think the purpose was to not loop through all AUPs on load - as there can be many - to do the replacement, and instead only copy the MTO over when needed. To me it seems like it would make the most sense to either leave the logic as is or just return the AUPs from the build with the MTOs. 

PPI does not depend on DM with this PR. ppi.mtoConfigMap is only ever attempter to be utilized when the mediaTypes object does not exist on the AUP. If someone outside of DM wanted to use this feature, the mtoConfigMap definition would still need to be done - and if not, it should log a Prebid error regardless if this was initialized as described or not.

2020-10-22 16:56 UTC, harpere commented on modules/ppi/hbInventory/aup/aup.js
> +    adUnitPattern.mediaTypes = pbjs.ppi.mtoConfigMap[adUnitPattern.mtoRevId].mediaTypes;
@FilipStamenkovic @mmoschovas We decided in the call yesterday to keep this logic, but I think it does need to change a bit to work more seamlessly without DM.  Maybe this:
```
try {
    adUnitPattern.mediaTypes = adUnitPattern.mediaTypes || pbjs.ppi.mtoConfigMap[adUnitPattern.mtoRevId].mediaTypes;
    delete adUnitPattern.mtoRevId;
  } catch (e) {
    utils.logError('[PPI] Unable to resolve the mediaTypes for adUnitPattern', adUnitPattern, e);
  }
return !!adUnitPattern.mediaTypes;
```
So if we don't have DM, and the MTO already exists, we use it.  Otherwise it tries to get it from the mtoConfigMap.

2020-10-22 17:12 UTC, harpere commented on modules/ppi/hbInventory/aup/aup.js
> +    adUnitPattern.mediaTypes = pbjs.ppi.mtoConfigMap[adUnitPattern.mtoRevId].mediaTypes;
@FilipStamenkovic @mmoschovas - we decided on the call yesterday to keep this logic.  And this function is never called if an MTO already exists (line 213), so should still work without DM.  But to be safe we could make the first line of the function this: 
```
if (adUnitPattern.mediaTypes) return true;
```

2020-10-23 12:48 UTC, aleksatr commented on modules/ppi/hbInventory/aup/aup.js
> +    if (match) match = addMtoToPattern(aup);
@mmoschovas what do you think about adding: 

```
addMtoToPattern(aup);
```

to L218? This way we don't need this `if` and we don't need to assign the result of this function to `match`.

2020-10-23 13:27 UTC, mmoschovas commented on modules/ppi/hbInventory/aup/aup.js
> +    if (match) match = addMtoToPattern(aup);
I left it prior to that return conditional so that if there was an MTO issue, it would not proceed to the sizes matching portion. If it is moved to the line you referenced, this will cause an issue when returned false. This means that if there is no mediaType Pattern on the AUP and either there is no MTO id reference or the reference doesnt exist the function will return false setting _match = false_. However, because is falls after the return condition, it can then pass the next check allowing it to continue as a match when it should have failed, thus holding an auction using this AUP.

2020-10-26 12:04 UTC, aleksatr commented on modules/ppi/hbInventory/aup/aup.js
> +    if (match) match = addMtoToPattern(aup);
@mmoschovas I guess it depends on how you look at AUPs without sizes, we had in mind to support this scenario, meaning AUPs with no sizes can be matched. In this case, sizes should be present inside the transaction object (hbInventory.sizes or from GPT slot object). Also, mind that sizes can be present in `mediaTypes.banner.responsiveSizes`, which takes priority over `mediaTypes.banner.sizes` when present. 
In general we didn't look at AUPs with no sizes as an error, we were assuming that in this case sizes will come from the transaction object or responsive sizes. This is why we have `!aupSizes || !aupSizes.length` inside the condition on L222:

```
if (!limitSizes || !limitSizes.length || !aupSizes || !aupSizes.length) {
      match = true;
    }
```

2020-11-16 04:55 UTC, harpere commented on modules/ppi/hbInventory/aup/aup.js
> +    if (match) match = addMtoToPattern(aup);
shouldn't `responsive sizes` already have been converted to actual `sizes` by this point?

2020-11-16 04:57 UTC, harpere commented on modules/ppi/hbInventory/aup/aup.js
> +    if (match) match = addMtoToPattern(aup);
@aleksatr can you give a specific, real world example of when the AUP would not have a mediaType defined?  It's not clear in my mind what the use case is.

2020-11-16 13:59 UTC, naegelin commented on modules/ppi/hbInventory/aup/aup.js
> +    if (match) match = addMtoToPattern(aup);
@harpere publishers who frequently A/B test layouts and size combinations (common scenario for some of our pubs) could theoretically want to not define any MTO sizes and instead pass them in at runtime based on the active layout + device combination.

2020-11-19 19:59 UTC, FilipStamenkovic approved these changes

2020-11-19 20:00 UTC, merged