Video playerSize filter update
rubicon-project/PPI pull request #4
Opened 2021-04-12 14:51 UTC by mmoschovas

## Type of change

- [ ] Bugfix
- [X ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

Update to include size validation on video mediaType playerSize as well as banner sizes

- test parameters for validating bids
```
{
  bidder: '<bidder name>',
  params: {
    // ...
  }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [ ] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

## Other information

2021-04-13 07:18 UTC, FilipStamenkovic approved these changes
LGTM

2021-04-13 18:35 UTC, mmoschovas commented
@FilipStamenkovic I noticed after that banner sizes were being deep set on these video patterns. I added a secondary change to aup.js to only deep set if the banner mediatype exists or video does not exist. Can you please take a look again when you have a chance

2021-04-14 10:05 UTC, FilipStamenkovic requested changes
Can you add some example of video AUPs, maybe in tests and/or integration examples we have for ppi?

2021-04-14 10:05 UTC, FilipStamenkovic commented on modules/ppi/hbInventory/aup/sizes.js
> +  let sizes = utils.deepAccess(aup, 'mediaTypes.banner.sizes') || utils.deepAccess(aup, 'mediaTypes.video.playerSize');
What will happen if some AUP has support for video and banner at the same time?  
I know pbjs has support for adUnits that have both media types, I'm not sure about dm.

2021-04-14 10:05 UTC, FilipStamenkovic commented on modules/ppi/hbInventory/aup/aup.js
> +    if (utils.deepAccess(adUnit, 'mediaTypes.banner') || !utils.deepAccess(adUnit, 'mediaTypes.video')) utils.deepSetValue(adUnit, 'mediaTypes.banner.sizes', sortSizes(aupSizes));
Can you break this line into more lines, it's 180 characters long?

2021-04-14 11:39 UTC, mmoschovas commented on modules/ppi/hbInventory/aup/sizes.js
> +  let sizes = utils.deepAccess(aup, 'mediaTypes.banner.sizes') || utils.deepAccess(aup, 'mediaTypes.video.playerSize');
If it supports both banner sizes should only be used for filtering. Outstream runs on banner so its playerSize should not be used to determine a size match. i.e. playerSize 640x480 can run in banner 300x250

2021-04-14 11:45 UTC, mmoschovas commented on modules/ppi/hbInventory/aup/aup.js
> +    if (utils.deepAccess(adUnit, 'mediaTypes.banner') || !utils.deepAccess(adUnit, 'mediaTypes.video')) utils.deepSetValue(adUnit, 'mediaTypes.banner.sizes', sortSizes(aupSizes));
Done

2021-04-16 11:35 UTC, FilipStamenkovic approved these changes

2021-04-16 11:36 UTC, merged